### ISSUE TITLE
Vanilla WebComponents aproaches: is there any real diference between “importing js from html” and “fetching html from js” file

### ISSUE THREAD

**Issue by jimisdrpc** [ayushgp/web-components-tutorial#6]
Really nice article. A bit sad you didn't evolve it (you could add unit and integration testing for instatnce). Kindly, could you explain why you update your first article? If you don't mind, could you try answer my question https://stackoverflow.com/questions/57379900/vanilla-webcomponents-aproaches-is-there-any-real-diference-between-importing ?

**Comment by ayushgp** [comment]
Hi Jim,

Glad you liked the articles :)

> A bit sad you didn't evolve it

I've not worked on web components since before I wrote these articles. I've not ever written Unit or Integration tests for the frontend, but I'll try to write those and add articles about them as well. 

> could you explain why you update your first article

As I've mentioned on the article, HTML imports were about to be removed from the browser based on the discussion at that time. The other ways to get around this problem is to either put the HTML in the JS file as a template string, but I don't like that approach because of the clutter it'll result in. 

Another approach that can be taken here is to configure your build such that you copy over the contents in your HTML file to components' JS file as part of your build. This will require some set up and a config maybe to keep track of all your components and corresponding htmls. I couldn't come up with anything other than these 3 approaches(Other 2 in the article's update). 

Let me know if you have any other queries or need any other help. 

Chrome team is coming up with a new approach **HTML Modules** as is being discussed here: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/ewfRSdqcOd8/w_Fr6rJ3DQAJ

But this is still under discussion. You can also look at Polymer and look at how that solves this problem. Hope this helps!
